### ISSUE TITLE
Typing in the middle of the input should insert a character, not replace

### ISSUE THREAD

**Issue by dbalatero** [sanniassin/react-input-mask#125]
@sanniassin I'm not sure if this is by design, but when you type in the middle of the input box, it will overwrite the next character instead of inserting the character you typed. This feels unexpected to me.

Here is a GIF: 
![input](https://user-images.githubusercontent.com/59429/36166921-f0085b40-10a8-11e8-8b5f-1c4a5da274fe.gif)

I'd expect to be able to insert a character in the middle of the input. Not quite sure what to do when the input is at max length. You could either:

* start replacing characters
* don't allow any more characters to be typed

**Comment by sanniassin** [comment]
@dbalatero It always replaces If you have non-empty `maskChar` (which is `_` by default). If it's empty, then it replaces only if input has reached max length. It's intentional behavior because actual insertion or removal in the middle of filled masked input often turns the whole value into a hard-to-read mess.

![out](https://user-images.githubusercontent.com/2291616/39360589-98d9e448-4a27-11e8-9211-5d31ea3f5c11.gif)

**Comment by fpoirier1** [comment]
I am facing the same issue as @dbalatero and I am not sure what to do to get the desired behavior. In @dbalatero's example, the input didn't reached the max length so we would assume that the caracter would inserted instead of replacing.

**Comment by jamespedid** [comment]
This provides worse behavior for end users who will have to retype the entire number if they follow the canonical pattern to replace a number, which is to delete the number they want and then put in a new one.
