### ISSUE TITLE
Accessibility issue with screen readers

### ISSUE THREAD

**Issue by bduebel** [sanniassin/react-input-mask#131]
Changing the input value on focus creates a nightmare scenario for screen readers.

**Comment by HenriqueLimas** [comment]
Is it possible to reopen this issue? We found an issue on safari for screen readers when the value is empty. VoiceOver reads the first character of the mask even with label and the input id are set properly. 

How to simulate (v2.0.4):
- On Safari desktop goes to https://l91y6.csb.app
- Enable VoiceOver (cmd + F5)
- With the tab key, focus on the input

Expected: The screen reader reads "Content selected, Telephone, edit text"
Actual: The screen reader reads "Open parenthesis"

Looking into the code and found out that this is happening because the library use the `defer()` for setting the selection.  [Code line](https://github.com/sanniassin/react-input-mask/blob/2.0.4/src/index.js#L279), removing the defer the screen reader reads it properly. 
Maybe we could run the `defer` only for androids.
