### ISSUE TITLE
Android Firefox: Mask characters inserted at randomly

### ISSUE THREAD

**Issue by jonashaag** [sanniassin/react-input-mask#83]
Our mask is `**99 9999 9999 9999 9999 99` for German IBANs.

We have an `onChange` handler that upper-cases the `value` (thus we use `InputElement` as controlled input).

Protocol of what I do, what I expect, what actually happens (| = cursor):

```
input: de|
expect: DE|
actual: DE|

input: de1|
expected: DE1|
actual: DE9|9

input: de12|
expected: DE12|
actual: DE99 2|9
```

If I remove these lines: https://github.com/sanniassin/react-input-mask/blob/3c66aa8483d74c5c300848432cf5668e51f1fe94/InputElement.js#L732 then the bug above goes away, but another bug appears:

```
input: de12|
expected: DE12|
actual: DE11 2|
```

**Comment by sanniassin** [comment]
@jonashaag Try to add `style={{ text-transform: uppercase }}` instead of uppercasing value in onChange handler.

When `value` prop is not equal to input value (and it's not because of case conversion) React have to update value at input DOM node which leads to some [weird issues](https://github.com/sanniassin/react-input-mask/issues/85#issuecomment-306908065). In your case updating input value from js code drives Firefox autocompletion crazy.

If you replace `react-input-mask` with regular input, enter "de12" and convert it to upper case in onChange then you'll see same issue.

**Comment by jonashaag** [comment]
Thanks for the pointer, I'll try that out!

**Comment by sanniassin** [comment]
Whoops, used CSS notation in js. It should be `style={{ textTransform: 'uppercase' }}' instead of `style={{ text-transform: uppercase }}`
