### ISSUE TITLE
Can I use your mask with other component? 

### ISSUE THREAD

**Issue by luckyraul** [sanniassin/react-input-mask#9]
for example with http://material-ui.com/#/components/text-fields ?

**Comment by sanniassin** [comment]
It depends on component. You can use react-input-mask with Material-UI because it allows us to override it's own <code>&lt;input/&gt;</code> element with children:
```js
var TextField = require('material-ui/lib/text-field');
var InputMask = require('react-input-mask');
var Input = React.createClass({
    render: function() {
        return (
            <TextField>
                <InputMask mask="99-99"/>
            </TextField>
        );
    }
});
```

Not sure if it's right way for Material-UI or undocumented feature. Found it in TextFIeld source code: https://github.com/callemall/material-ui/blob/master/src/text-field.jsx#L334-L336
